manually check for dockerfile

diff --git a/.github/workflows/build_and_push_csms.yml b/.github/workflows/build_and_push_csms.yml
--- a/.github/workflows/build_and_push_csms.yml
+++ b/.github/workflows/build_and_push_csms.yml
@@ -157,6 +157,14 @@ jobs:
       - name: List files in context
         run: ls -R ./citrineos-csms/Server
 
+      #add a step to see if dockerfile exists in contect
+      - name: Check if Dockerfile exists
+        run: |
+          if [ ! -f ${{ matrix.context }}/${{ matrix.dockerfile }} ]; then
+            echo "Error: Dockerfile not found at ${{ matrix.context }}/${{ matrix.dockerfile }}"
+            exit 1
+          fi
+
       - name: Build and export to Docker
         uses: docker/build-push-action@v6
         with:
